#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --config ./config/commitlint.config.js --edit "$1"

# commit_types=("build" "chore" "ci" "docs" "feat" "fix" "perf" "refactor" "revert" "style" "test")
# emoji_types=(":building_construction:" ":wrench:" ":construction_worker:" ":memo:" ":sparkles:" ":bug:" ":zap:" ":recycle:" ":rewind:" ":lipstick:" ":white_check_mark:")

# match_index=0
# index=0

# for item in ${commit_types[@]}; do
#   type_regex="^${item}"

#   if [[ $1 =~ $type_regex ]]; then
#     let match_index=$index;
#   fi

#   let index=${index}+1
# done

# match_emoji=${emoji_types[$match_index]}

# res_msg=$(echo $1 | sed "s/^${commit_types[$match_index]}/"$match_emoji"/")

# # 稍显拙劣 不知如何直接修改 msg
# git commit --amend -m "fe." --no-verify
